import Foundation
import Observation

/// Drives the success screen. On `load()` it builds the `AISelfRequest`
/// from the captured media and calls the backend; `IDCardLoadStateView`
/// renders `loadState` (loading / loaded / error). `dismiss()` resets the
/// onboarding stack so the user lands back on sign-in.
@Observable
final class SuccessViewModel {
    /// Three-state machine for the card-creation request.
    enum LoadState: Equatable {
        case loading
        case loaded(IDCard)
        case error(String)
    }

    private(set) var loadState: LoadState = .loading
    var showShare: Bool = false

    let phone: E164
    let selfieURL: URL
    let voiceURL: URL
    let openMessages: () -> Void
    private let onDismiss: () -> Void
    private let client: any OnboardingClient

    init(
        client: any OnboardingClient,
        phone: E164,
        selfieURL: URL,
        voiceURL: URL,
        openMessages: @escaping () -> Void,
        onDismiss: @escaping () -> Void
    ) {
        self.client = client
        self.phone = phone
        self.selfieURL = selfieURL
        self.voiceURL = voiceURL
        self.openMessages = openMessages
        self.onDismiss = onDismiss
    }

    func load() async {
        loadState = .loading
        do {
            // The selfie and voice URLs become server-side keys after upload.
            // The mock client echoes them back; the live client will swap them
            // out for an avatar generated by the backend.
            let request = AISelfRequest(
                phone: phone.e164String,
                selfieKey: selfieURL.absoluteString,
                voiceKey: voiceURL.absoluteString
            )
            let card = try await client.createAISelf(request)
            loadState = .loaded(card)
        } catch {
            loadState = .error((error as? LocalizedError)?.errorDescription ?? error.localizedDescription)
        }
    }

    func dismiss() { onDismiss() }
}
